/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VOpylm7kxbl
 */
import {CardContent, Card} from "@/components/ui/card";
import {useState} from "react";

export function SuggestionComponent({items, setItems}: any) {
  const [submitted, setSubmitted] = useState(false);
  const [newItem, setnewItem] = useState({
    name: "",
    suggestion: "",
    score: 0,
  });
  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    event.preventDefault();
    const {name, value} = event.target;

    // Assuming you have separate input elements for 'name' and 'suggestion'
    setnewItem((prevItem) => ({
      ...prevItem,
      [name]: value,
    }));

    console.log(newItem);
  }

  const submitNewItem = async (event: any) => {
    event.preventDefault();
    setItems([...items, newItem]);
    setSubmitted(true);

    try {
      const response = await fetch("/api/item", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newItem),
      });

      if (response.ok) {
        console.log("Data submitted successfully!");
        // You can perform additional actions here after successful submission
      } else {
        console.error("Failed to submit data. Status:", response.status);
        // You can handle error cases here
      }
    } catch (error) {
      console.error("An error occurred:", error);
      // Handle other types of errors here
    }
  };

  return (
    <Card className="p-4 mb-4 border-gray-200 shadow-lg">
      <CardContent className="flex flex-row items-start gap-4">
        <form className="w-full">
          <label
            className="block text-sm font-medium text-gray-700 mb-2"
            htmlFor="name"
          >
            Votre Nom & Prénom :
          </label>
          <input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-4"
            id="name"
            placeholder=""
            type="text"
            required
            name="name"
            value={newItem.name}
            onChange={handleChange}
          />
          <label
            className="block text-sm font-medium text-gray-700 mb-2"
            htmlFor="suggestion"
          >
            Votre Menu Suggesstion (Pas Votre Nom) :
          </label>
          <input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-4"
            id="suggestion"
            placeholder="مقروتة كذابة"
            required
            type="text"
            name="suggestion"
            value={newItem.suggestion}
            onChange={handleChange}
          />
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            type="button"
            onClick={submitNewItem}
            disabled={newItem.suggestion.length == 0}
          >
            Submit
          </button>
          {submitted && (
            <div className="text-green-500">
              Votre Suggestion a été submis avec Succès
            </div>
          )}
        </form>
      </CardContent>
    </Card>
  );
}
