import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Zeta Engineering | Food Review",
  description: "Generated by Zeta Engineering | Food Review",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="relative">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
